import sys,string
M=len(sys.argv)
list =["Urinary Incontinence, Urge",
"Oral Hemorrhage",
"Gastroparesis",
"Necrolytic Migratory Erythema",
"Hearing Loss, Sudden",
"Cyanosis",
"Hot Flashes",
"Overweight",
"Cafe-au-Lait Spots",
"Sneezing",
"Hyperphagia",
"Voice Disorders",
"Vocal Cord Paralysis",
"Apraxia, Ideomotor",
"Korsakoff Syndrome",
"Tinnitus",
"Eye Hemorrhage",
"Neuralgia, Postherpetic",
"Spasm",
"Phantom Limb",
"Perceptual Disorders",
"Aphasia, Conduction",
"Space Motion Sickness",
"Hyperkinesis",
"Hemianopsia",
"Headache",
"Aphasia, Primary Progressive",
"Taste Disorders",
"Hearing Loss, Mixed Conductive-Sensorineural",
"Fasciculation",
"Myoclonus",
"Cardiac Output, Low",
"Polyuria",
"Flatulence",
"Somatosensory Disorders",
"Deafness",
"Reflex, Abnormal",
"Amnesia",
"Mutism",
"Alexia, Pure",
"Decerebrate State",
"Hypoventilation",
"Horner Syndrome",
"Gerstmann Syndrome",
"Syncope",
"Weight Gain",
"Dyspnea",
"Hearing Loss, Noise-Induced",
"Stuttering",
"Echolalia",
"Edema, Cardiac",
"Infantile Apparent Life-Threatening Event",
"Urinoma",
"Urinary Incontinence",
"Coprophagia",
"Sleep Disorders",
"Purpura, Thrombotic Thrombocytopenic",
"Encopresis",
"Pseudophakia",
"Sciatica",
"Hypothermia",
"Sweating Sickness",
"Prostatism",
"Vomiting, Anticipatory",
"Diarrhea",
"Dysphonia",
"Hearing Loss",
"Hearing Disorders",
"Dizziness",
"Paraparesis, Spastic",
"Slit Ventricle Syndrome",
"Striae Distensae",
"Blindness",
"Amblyopia",
"Muscle Weakness",
"Amnesia, Anterograde",
"Muscle Hypertonia",
"Auditory Perceptual Disorders",
"Amnesia, Retrograde",
"Aphasia",
"Communication Disorders",
"Weight Loss",
"Ecchymosis",
"Vision, Low",
"Hyperesthesia",
"Hyperalgesia",
"Muscular Atrophy",
"Muscle Hypotonia",
"Dysarthria",
"Apraxias",
"Tonic Pupil",
"Muscle Cramp",
"Body Weight Changes",
"Jaundice, Obstructive",
"Hyperoxia",
"Bulimia",
"Constipation",
"Paresis",
"Hypergammaglobulinemia",
"Amnesia, Transient Global",
"Athetosis",
"Waterhouse-Friderichsen Syndrome",
"Hypesthesia",
"Pain, Referred",
"Neck Pain",
"Renal Colic",
"Paraparesis",
"Tetany",
"Sarcopenia",
"Syncope, Vasovagal",
"Articulation Disorders",
"Purpura, Thrombocytopenic",
"Eructation",
"Usher Syndromes",
"Presbycusis",
"Respiratory Paralysis",
"Learning Disorders",
"Aphasia, Wernicke",
"Neurobehavioral Manifestations",
"Ataxia",
"Cachexia",
"Vomiting",
"Halitosis",
"Hearing Loss, Sensorineural",
"Tremor",
"Reflex, Babinski",
"Coma",
"Dyslexia, Acquired",
"Hypokinesia",
"Fatigue",
"Hydrops Fetalis",
"Dyspnea, Paroxysmal",
"Vertigo",
"Persistent Vegetative State",
"Psychomotor Agitation",
"Diplopia",
"Metatarsalgia",
"Quadriplegia",
"Neuralgia",
"Stupor",
"Neurologic Manifestations",
"Edema",
"Livedo Reticularis",
"Cheyne-Stokes Respiration",
"Chest Pain",
"Low Back Pain",
"Catalepsy",
"Hypocapnia",
"Shoulder Pain",
"Unconsciousness",
"Speech Disorders",
"Hearing Loss, Central",
"Agraphia",
"Mobility Limitation",
"Chills",
"Oliguria",
"Hypercalciuria",
"Earache",
"Oral Manifestations",
"Torticollis",
"Heart Murmurs",
"Gagging",
"Dyspepsia",
"Diarrhea, Infantile",
"Anomia",
"Gait Disorders, Neurologic",
"Tics",
"Proteinuria",
"Reticulocytosis",
"Color Vision Defects",
"Paresthesia",
"Mental Retardation",
"Intermittent Claudication",
"Agnosia",
"Labor Pain",
"Back Pain",
"Myokymia",
"Prosopagnosia",
"Lethargy",
"Gait Apraxia",
"Flushing",
"Thinness",
"Snoring",
"Hyperventilation",
"Hematemesis",
"Deaf-Blind Disorders",
"Aging, Premature",
"Ageusia",
"Olfaction Disorders",
"Primary Progressive Nonfluent Aphasia",
"Cough",
"Catatonia",
"Gait Ataxia",
"Fetal Weight",
"Fetal Macrosomia",
"Flank Pain",
"Toothache",
"Purpura, Schoenlein-Henoch",
"Tinea Pedis",
"Colic",
"Abdominal Pain",
"Sensation Disorders",
"Pupil Disorders",
"Brown-Sequard Syndrome",
"Dyslexia",
"Akathisia, Drug-Induced",
"Purpura, Thrombocytopenic, Idiopathic",
"Respiratory Sounds",
"Acute Coronary Syndrome",
"Photophobia",
"Amaurosis Fugax",
"Hyperacusis",
"Pseudobulbar Palsy",
"Ophthalmoplegia",
"Memory Disorders",
"Albuminuria",
"Aerophagy",
"Sleep Deprivation",
"Hearing Loss, High-Frequency",
"Facial Pain",
"Alien Hand Syndrome",
"Fetal Distress",
"Cardiac Output, High",
"Glossalgia",
"Hearing Loss, Conductive",
"Paraplegia",
"Supranuclear Palsy, Progressive",
"Myotonia",
"Aphasia, Broca",
"Meningism",
"Hemiplegia",
"Urinary Incontinence, Stress",
"Purpura Fulminans",
"Pallor",
"Anoxia",
"Susac Syndrome",
"Hyperemesis Gravidarum",
"Morning Sickness",
"Pelvic Pain",
"Angina Pectoris, Variant",
"Scotoma",
"Paralysis",
"Hemifacial Spasm",
"Obesity, Morbid",
"Asthenia",
"Respiratory Aspiration",
"Mouth Breathing",
"Pain, Postoperative",
"Psychophysiologic Disorders",
"Dyskinesias",
"Hemoglobinuria",
"Jaundice",
"Hemoptysis",
"Angina, Unstable",
"Pain, Intractable",
"Muscle Spasticity",
"Hallucinations",
"Consciousness Disorders",
"Delirium",
"Confusion",
"Language Development Disorders",
"Dystonia",
"Mental Fatigue",
"Pruritus",
"Anisocoria",
"Trismus",
"Feminization",
"Obesity",
"Urinary Bladder, Overactive",
"Arthralgia",
"Hoarseness",
"Piriformis Muscle Syndrome",
"Eye Pain",
"Eye Manifestations",
"Purpura, Hyperglobulinemic",
"Vision Disorders",
"Virilism",
"Anorexia",
"Blindness, Cortical",
"Dysgeusia",
"Motion Sickness",
"Heartburn",
"Dysmenorrhea",
"Seizures",
"Miosis",
"Ophthalmoplegia, Chronic Progressive External",
"Psychomotor Disorders",
"Synkinesis",
"Body Weight",
"Nocturia",
"Hiccup",
"Urinary Bladder, Neurogenic",
"Hearing Loss, Functional",
"Skin Manifestations",
"Nausea",
"Angina Pectoris",
"Abdomen, Acute",
"Hearing Loss, Unilateral",
"Illusions",
"Cerebrospinal Fluid Rhinorrhea",
"Fever",
"Purpura",
"Apnea",
"Hearing Loss, Bilateral",
"Facial Paralysis",
"Pain",
"Orthostatic Intolerance",
"Muscle Rigidity",
"Emaciation",
"Birth Weight",
"Fever of Unknown Origin",
"Hirsutism",
"Postoperative Nausea and Vomiting",
"Cerebrospinal Fluid Otorrhea",
"Systolic Murmurs",
"Dysuria",
"Hypercapnia",
"Fetal Hypoxia",
"Chorea",
"Aphonia",
"Language Disorders",
"Cerebellar Ataxia"]

def main():
	if(M>2):
		sys.stdout.write(string.lower(list[int(sys.argv[1])]))
		sys.stdout.write(";")
		for i in range(2,M-1):
			sys.stdout.write(string.lower(list[int(sys.argv[i])]))
			sys.stdout.write(";")
		sys.stdout.write(string.lower(list[int(sys.argv[M-1])]))
	#print M;

if __name__ == '__main__':
	main();
